### ISSUE TITLE
Problem with Package 'EnterpriseLibrary.TransientFaultHandling 6.0.1304'

### ISSUE THREAD

**Issue by mpostol** [Drutol/CrossHMI#17]
Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1701	Package 'EnterpriseLibrary.TransientFaultHandling 6.0.1304' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.	CrossHMI.LibraryIntegration.AzureGateway	C:\Users\mpostol\source\VS\CrossHMI\CrossHMI\CrossHMI.LibraryIntegration.AzureGateway\CrossHMI.LibraryIntegration.AzureGateway.csproj	1

**Comment by Drutol** [comment]
Looks like some leftover from testing. Removed.
