### ISSUE TITLE
Azure reference in the CrossHMI.AzureGatewayService

### ISSUE THREAD

**Issue by mpostol** [Drutol/CrossHMI#20]
This project should not have references to the Azure SDK but it has in

1. CrossHMI.AzureGatewayService.Devices.Boiler
2. CrossHMI.AzureGatewayService.Infrastructure.Configuration.BoilerRepositoryDetails

> Note: The project doesn't have references to Azure SDK ?!

The only Azure related functionality (including but not limiting to configuration) shall be located in the `CrossHMI.LibraryIntegration.AzureGateway`

**Comment by mpostol** [comment]
Using the Class view the references are present.
![Bez tytułu](https://user-images.githubusercontent.com/11937915/89459804-87e9b600-d769-11ea-9eec-284db1a33ba7.png)

**Comment by Drutol** [comment]
Fixed.
