### ISSUE TITLE
NetworkDeviceBase - wrong implementation of the Dictionary

### ISSUE THREAD

**Issue by mpostol** [Drutol/CrossHMI#21]
In the code 
```C#

 Dictionary<Type, Dictionary<string, (ProcessVariableAttribute Attribute, PropertyInfo Property)>>
            _propertyMappings =
                new Dictionary<Type, Dictionary<string, (ProcessVariableAttribute Attribute, PropertyInfo Property)>>(); //TODO #MP Type cannot be used as the Key

```
according to the requirements defined for the [Dictionary](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Collections.Generic.Dictionary%602)%3Bk(SolutionItemsProject)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=netcore-3.1#remarks) `Type` cannot be used as the TKey

**Comment by Drutol** [comment]
>Dictionary<TKey,TValue> requires an equality implementation to determine whether keys are equal. You can specify an implementation of the IEqualityComparer<T> generic interface by using a constructor that accepts a comparer parameter; if you do not specify an implementation, the default generic equality comparer EqualityComparer<T>.Default is used.

It exaplains that there's `EqualityComparer<T>.Default` used when none is specified.

**Comment by mpostol** [comment]
`EqualityComparer<T>.Default` expects implementation of ` IEquatable<T>` but Type doesn't provide this.
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.equalitycomparer-1.default?view=netstandard-2.1
There is default behavior but it could change in time and in a different framework

**Comment by Drutol** [comment]
That's true but in the same article it reads:
> Otherwise, it returns an EqualityComparer<T> that uses the overrides of Object.Equals and Object.GetHashCode provided by T.

If behaviour of `Equals` and `GetHashCode` gets changed in time then I think that would be one of the lesser issues. It is true that  in different runtimes the hashcodes of `Type` will be different but as this is not persisted/serialized in any way this behaviour is of no concern.

`Type` provides overrides for both `GetHashCode` and `Equals` which according to documentation perform as expected.
